#!/usr/bin/env bash

if
  [[ -s "/home/ronick/.rvm/gems/ruby-2.2.2@rails4.2.3/environment" ]]
then
  source "/home/ronick/.rvm/gems/ruby-2.2.2@rails4.2.3/environment"
  exec bundler "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ronick/.rvm/gems/ruby-2.2.2@rails4.2.3/environment'" >&2
  exit 1
fi
