# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1459584264);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1459584384);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1459591104);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1459584144);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1459584024);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1459584504);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1459602237003");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1459603977003");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1459602239033");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1459605839033");
user_pref("browser.search.countryCode", "UA");
user_pref("browser.search.region", "UA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160209234642");
user_pref("browser.slowStartup.averageTime", 9081);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20160209234642");
user_pref("browser.startup.homepage_override.mstone", "44.0.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1459670183877");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1459583848831");
user_pref("datareporting.policy.firstRunTime", "1459583783877");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 7846);
user_pref("datareporting.sessions.current.main", 1435);
user_pref("datareporting.sessions.current.sessionRestored", 7476);
user_pref("datareporting.sessions.current.startTime", "1459602223541");
user_pref("datareporting.sessions.current.totalTime", 33);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1459583779157,\"a\":232,\"t\":3797,\"c\":true,\"m\":1435,\"fp\":9870,\"sr\":9659}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1459588027183,\"a\":511,\"t\":4540,\"c\":false,\"m\":2705,\"fp\":10698,\"sr\":10367}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"44.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"44.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1459584265);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160106.01");
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455751010000,\"mt\":1455064035000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455064750000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"44.0.2\",\"st\":1455064750000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("gecko.buildID", "20160209234642");
user_pref("gecko.mstone", "44.0.2");
user_pref("gfx.crash-guard.glcontext.appVersion", "44.0.2");
user_pref("gfx.crash-guard.glcontext.deviceID", "Mesa DRI Intel(R) Sandybridge Mobile ");
user_pref("gfx.crash-guard.glcontext.driverVersion", "3.0 Mesa 11.0.2");
user_pref("gfx.crash-guard.status.glcontext", 1);
user_pref("idle.lastDailyNotification", 1459583970);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1459583850);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160209234642");
user_pref("media.gmp-manager.lastCheck", 1459583849);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1459583971);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1459583970);
user_pref("toolkit.startup.last_success", 1459602224);
user_pref("toolkit.telemetry.cachedClientID", "dfb6c3ed-3fc8-4132-b23f-8d7b6aa60d63");
user_pref("toolkit.telemetry.previousBuildID", "20160209234642");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
